### ISSUE TITLE
Verfify RMG

### ISSUE THREAD

**Issue by JakobDev** [flathub/com.github.Rosalie241.RMG#32]
Flathub has now a new Website which includes new features such as Verification. Verification means, that the Flatpak is a official one that is supported by the Developer. You should verify RMG. Just go to [flathub.org](https://flathub.org), log in with your GitHub Account, open the Developer Settings and select "Login Provider verfification".

**Comment by Rosalie241** [comment]
It should be verified now, thank you :heart:
